### ISSUE TITLE
Cant add device (unexpected error)

### ISSUE THREAD

**Issue by seb07-cloud** [turlvo/KuKuHarmony#3]
physicalgraph.app.exception.UnknownDeviceTypeException: Device type 'KuKu Harmony_Fan' in namespace 'turlvo' not found. @line 512 (initializeChild)

**Comment by turlvo** [comment]
Hi
You need to add a related DTH.
Please add all DTH related to Hatmony.

**Comment by seb07-cloud** [comment]
sry my bad ... thx for ur great work
